import React, { useState, useEffect } from 'react';
import {
  Shield,
  KeyRound,
  Building2,
  Calendar,
  AlertTriangle,
  ArrowRight,
  RefreshCw,
  LogOut,
  Sparkles,
  Lock,
  CheckCircle2,
  ArrowLeft
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext.js';
import { getAdminControlInfo, enterAdminControl } from '../../services/api.js';
import { AdminAuthModal } from '../auth/AdminAuthModal.js';
import { ThemeToggle } from '../common/ThemeToggle.js';

interface AdminControlEntryViewProps {
  adminToken: string;
  onSuccess: (data: { eventId: string; event: any; rounds: any[]; participantLink: string; adminLink: string }) => void;
  onBackToHome: () => void;
}

export const AdminControlEntryView: React.FC<AdminControlEntryViewProps> = ({
  adminToken,
  onSuccess,
  onBackToHome
}) => {
  const { user, logout } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [controlInfo, setControlInfo] = useState<{
    eventName: string;
    collegeName: string;
    status: string;
  } | null>(null);

  const [eventKey, setEventKey] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [authModalOpen, setAuthModalOpen] = useState(false);

  useEffect(() => {
    let isMounted = true;
    setLoading(true);
    setError(null);

    getAdminControlInfo(adminToken)
      .then((data) => {
        if (!isMounted) return;
        setControlInfo({
          eventName: data.eventName,
          collegeName: data.collegeName,
          status: data.status
        });
      })
      .catch((err) => {
        if (!isMounted) return;
        setError(err.response?.data?.error || 'Invalid or expired tournament control link.');
      })
      .finally(() => {
        if (isMounted) setLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [adminToken]);

  const handleEnterControl = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!eventKey.trim()) {
      setSubmitError('Please enter the Event Key (Event Code).');
      return;
    }

    setSubmitting(true);
    setSubmitError(null);

    try {
      const data = await enterAdminControl({
        adminToken: adminToken.trim(),
        eventCode: eventKey.trim().toUpperCase()
      });
      onSuccess(data);
    } catch (err: any) {
      setSubmitError(
        err.response?.data?.error || 'Failed to authenticate and enter Event Control Center.'
      );
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#090d16] flex items-center justify-center p-4">
        <div className="bg-[#0f172a] border border-slate-800 rounded-2xl p-8 max-w-md w-full text-center space-y-4 shadow-2xl">
          <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center mx-auto text-indigo-400">
            <RefreshCw className="w-6 h-6 animate-spin" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white">Validating Control Access</h2>
            <p className="text-sm text-slate-400 mt-1">
              Verifying private tournament token and access parameters...
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#090d16] flex items-center justify-center p-4">
        <div className="bg-[#0f172a] border border-rose-500/30 rounded-2xl p-8 max-w-md w-full text-center space-y-4 shadow-2xl">
          <div className="w-12 h-12 rounded-2xl bg-rose-500/10 border border-rose-500/30 flex items-center justify-center mx-auto text-rose-400">
            <AlertTriangle className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white">Invalid or Expired Link</h2>
            <p className="text-sm text-rose-300 mt-1 font-mono bg-rose-950/40 p-3 rounded-xl border border-rose-900/50">
              {error}
            </p>
          </div>
          <p className="text-xs text-slate-400">
            Private tournament management links are single-destination and can be regenerated by the event organizer at any time.
          </p>
          <div className="pt-2">
            <button
              onClick={onBackToHome}
              className="w-full py-2.5 px-4 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 transition shadow-lg shadow-indigo-600/30 flex items-center justify-center gap-2"
            >
              <ArrowLeft className="w-4 h-4" />
              Return to Debug Arena Home
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#090d16] text-slate-100 flex flex-col justify-between relative overflow-hidden font-sans">
      {/* Background glow accents */}
      <div className="absolute top-[-10%] left-[-10%] w-[45%] h-[45%] rounded-full bg-indigo-600/10 blur-[130px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[45%] h-[45%] rounded-full bg-cyan-600/10 blur-[130px] pointer-events-none" />

      {/* Navigation Header */}
      <header className="border-b border-slate-800/80 bg-[#0c1222]/80 backdrop-blur-md px-6 py-4 flex items-center justify-between sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <button
            onClick={onBackToHome}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800/60 transition"
            title="Return to Home"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 to-cyan-500 flex items-center justify-center text-white font-bold text-base shadow-lg shadow-indigo-500/20">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <span className="font-bold text-white tracking-tight text-base flex items-center gap-1.5">
                Debug Arena <span className="text-xs px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 font-mono font-medium border border-indigo-500/30">Control Center</span>
              </span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <ThemeToggle />
          {user && (
            <div className="flex items-center gap-2 pl-2 border-l border-slate-800">
              <div className="text-right hidden sm:block">
                <div className="text-xs font-semibold text-white">{user.username}</div>
                <div className="text-[10px] text-indigo-400 uppercase font-mono tracking-wider">{user.role}</div>
              </div>
              <button
                onClick={() => logout()}
                className="p-2 rounded-xl text-slate-400 hover:text-rose-400 hover:bg-rose-500/10 transition"
                title="Sign Out"
              >
                <LogOut className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 flex items-center justify-center p-4 sm:p-6 z-10">
        <div className="max-w-xl w-full">
          <div className="bg-[#0f172a]/95 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl backdrop-blur-xl relative overflow-hidden">
            {/* Header Badge */}
            <div className="flex items-center justify-between gap-2 mb-6">
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-slate-800/80 border border-slate-700/60 text-xs font-medium text-slate-300">
                <Building2 className="w-3.5 h-3.5 text-indigo-400" />
                <span>{controlInfo?.collegeName || 'Institution'}</span>
              </div>
              <span className={`text-[11px] font-mono px-2.5 py-1 rounded-full uppercase tracking-wider font-semibold border ${
                controlInfo?.status === 'live'
                  ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30'
                  : controlInfo?.status === 'ready'
                  ? 'bg-amber-500/20 text-amber-300 border-amber-500/30'
                  : 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30'
              }`}>
                {controlInfo?.status || 'Active'}
              </span>
            </div>

            {/* Event Name */}
            <div className="mb-6">
              <h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight leading-tight">
                {controlInfo?.eventName}
              </h1>
              <p className="text-sm text-slate-400 mt-1.5 leading-relaxed">
                Tournament Command & Live Evaluation Control. Authorize below to manage rounds, monitor participants, and control the live event.
              </p>
            </div>

            {/* State 1: User Not Logged In */}
            {!user && (
              <div className="space-y-5 bg-slate-900/60 border border-slate-800 rounded-2xl p-6 text-center">
                <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center mx-auto text-indigo-400">
                  <Lock className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-white">Administrator Authentication Required</h3>
                  <p className="text-xs text-slate-400 mt-1 max-w-sm mx-auto">
                    To access this event workspace, please sign in with your organizer or administrator credentials.
                  </p>
                </div>
                <button
                  onClick={() => setAuthModalOpen(true)}
                  className="w-full py-3 px-4 rounded-xl text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-500 transition shadow-lg shadow-indigo-600/30 flex items-center justify-center gap-2"
                >
                  <Shield className="w-4 h-4" />
                  Sign In as Administrator
                </button>
              </div>
            )}

            {/* State 2: Logged in as Participant (Blocked) */}
            {user && user.role === 'participant' && (
              <div className="space-y-4 bg-amber-950/30 border border-amber-500/30 rounded-2xl p-6 text-center">
                <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center mx-auto text-amber-400">
                  <AlertTriangle className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-amber-300">Contestant Account Detected</h3>
                  <p className="text-xs text-amber-200/80 mt-1">
                    You are signed in as <span className="font-mono text-amber-100 font-semibold">{user.username}</span>. Contestants are strictly prohibited from entering event administrative controls.
                  </p>
                </div>
                <button
                  onClick={() => {
                    logout();
                    setAuthModalOpen(true);
                  }}
                  className="w-full py-2.5 px-4 rounded-xl text-xs font-semibold text-white bg-slate-800 hover:bg-slate-700 border border-slate-700 transition flex items-center justify-center gap-2"
                >
                  <LogOut className="w-4 h-4" />
                  Switch to Administrator Account
                </button>
              </div>
            )}

            {/* State 3: Logged in as Admin / Organizer -> Enter Event Key */}
            {user && user.role !== 'participant' && (
              <form onSubmit={handleEnterControl} className="space-y-5">
                <div className="bg-indigo-950/20 border border-indigo-500/20 rounded-2xl p-4 flex items-start gap-3">
                  <KeyRound className="w-5 h-5 text-indigo-400 flex-shrink-0 mt-0.5" />
                  <div className="text-xs text-slate-300 space-y-1">
                    <p className="font-semibold text-indigo-200">Private Verification Step</p>
                    <p className="text-slate-400">
                      Enter the confidential <strong className="text-white">Event Key (Event Code)</strong> assigned to this tournament to unlock its administrative console.
                    </p>
                  </div>
                </div>

                {submitError && (
                  <div className="p-3.5 rounded-xl bg-rose-950/40 border border-rose-900/50 text-rose-300 text-xs flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 flex-shrink-0 text-rose-400" />
                    <span>{submitError}</span>
                  </div>
                )}

                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider">
                    Event Key (Event Code)
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={eventKey}
                      onChange={(e) => setEventKey(e.target.value.toUpperCase())}
                      placeholder="e.g. TECH26-ALPHA"
                      autoFocus
                      className="w-full px-4 py-3.5 bg-slate-900/90 border border-slate-700 rounded-xl text-white font-mono text-base tracking-wider focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition uppercase"
                    />
                    <div className="absolute right-3.5 top-3.5 text-slate-500 text-xs font-mono">
                      KEY
                    </div>
                  </div>
                  <p className="text-[11px] text-slate-500">
                    Case-insensitive. Provided during event creation or visible in the organizer dashboard.
                  </p>
                </div>

                <button
                  type="submit"
                  disabled={submitting || !eventKey.trim()}
                  className="w-full py-3.5 px-4 rounded-xl text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed transition shadow-lg shadow-indigo-600/30 flex items-center justify-center gap-2"
                >
                  {submitting ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      Unlocking Event Console...
                    </>
                  ) : (
                    <>
                      Enter Event Control Center
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </form>
            )}

            {/* Bottom Security Note */}
            <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center justify-between text-[11px] text-slate-500">
              <span className="flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5 text-indigo-400" />
                Cryptographically Isolated Workspace
              </span>
              <span>Audit Logged</span>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 py-4 px-6 text-center text-xs text-slate-500 z-10">
        Debug Arena &copy; {new Date().getFullYear()} &bull; Multi-College Competitive Engineering Platform
      </footer>

      {/* Admin Auth Modal if needed */}
      <AdminAuthModal
        isOpen={authModalOpen}
        onClose={() => setAuthModalOpen(false)}
      />
    </div>
  );
};
